pipeline {
    agent any

    tools {
        nodejs "Node 10.19.0"
    }

    environment {
        nodeVersion = "Node 10.19.0"
    }

    stages {

        // stage ('Unit Test') {
        //     steps {
        //         nodejs(nodeJSInstallationName: "${nodeVersion}") {
        //             sh 'npm install'
        //             sh 'USE_CHROME=1 npm run ci-test'
        //         }
        //     }
        // }

        stage ('Create Docker Image') {
            steps {
                sh 'docker build . -t timeoff:latest'
            }
        }

        stage ('Create ACR on Azure') {
            steps {
                dir("devops/infrastructure/azure-container-registry"){
                    withCredentials([string(credentialsId: 'az-storage-account-key', variable: 'ACCESS_KEY')]) { //set SECRET with the credential content
                        sh """sed -i "s|#{ACCESS_KEY}#|${ACCESS_KEY}|g" 00-backend.tf"""
                    }
                    withCredentials([azureServicePrincipal('az-areizas')]){
                        sh """sed -i "s|#{AZURE_SUBSCRIPTION_ID}#|${AZURE_SUBSCRIPTION_ID}|g" 01-dev.auto.tfvars"""
                        sh """sed -i "s|#{AZURE_CLIENT_ID}#|${AZURE_CLIENT_ID}|g" 01-dev.auto.tfvars"""
                        sh """sed -i "s|#{AZURE_CLIENT_SECRET}#|${AZURE_CLIENT_SECRET}|g" 01-dev.auto.tfvars"""
                        sh """sed -i "s|#{AZURE_TENANT_ID}#|${AZURE_TENANT_ID}|g" 01-dev.auto.tfvars"""
                    }
                    sh "terraform init"
                    sh "terraform apply -auto-approve"
                }
            }
        }

        stage ('Push Docker Images to Azure ACR') {
            steps {
                withCredentials([azureServicePrincipal('az-areizas')]){
                    sh 'az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID'
                    sh 'az acr login --name acrareizas'
                    sh 'docker tag timeoff:latest acrareizas.azurecr.io/timeoff:latest'
                    sh 'docker push acrareizas.azurecr.io/timeoff:latest'
                } 

            }
        }

    }
}



