pipeline {
    agent any

    tools {
        nodejs "Node 10.19.0"
    }

    environment {
        nodeVersion = "Node 10.19.0"
    }

    stages {

        // stage ('Unit Test') {
        //     steps {
        //         nodejs(nodeJSInstallationName: "${nodeVersion}") {
        //             sh 'npm install'
        //             sh 'USE_CHROME=1 npm run ci-test'
        //         }
        //     }
        // }

        stage ('Create Docker Image') {
            steps {
                sh 'docker build . -t timeoff:latest'
            }
        }

    }
}



